version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-eventdriven-app
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: ['redis-server', '--requirepass', 'mysecurepassword']
    environment:
      REDIS_PASSWORD: mysecurepassword
    expose:
      - 6379

  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - '1883:1883' # default mqtt port
      - '9001:9001' # default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:ro # config dosyasını doğru şekilde bağlama
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
